theme: jekyll-theme-tactile
title: Daniel J. Banko-Ferran
description:
social:
  name: Daniel Banko
  links:
    - https://www.linkedin.com/in/daniel-banko
    - https://www.facebook.com/danielJbanko
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
